name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2

      - name: CI
        run: deno task ci

      # - name: Run tests
      #   run: deno test

      # - name: Publish (dry run)
      #   run: deno publish --dry-run
